modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
modId = "example_mod"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
A very cool multi-line description!
'''
#logoFile = ""

[[dependencies.example_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.example_mod]]
modId="mega_showdown"
mandatory=true
versionRange="[3.8.3-release-neoforge,)"
ordering="AFTER"
side="BOTH"
