modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
modId = "examplemod"
version = "${version}"
displayName = "ExampleMOD"
authors = "Me!"
description = '''
AllTheMons is a collaborative effort from many contributors to add as many Pokemon as possible to Cobblemon. All of the addons below have been modified to ensure that there's no overlap, which prevents game-breaking bugs/crashes you would experience without AllTheMons.
'''
#logoFile = ""

[[dependencies.atmxmsd]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.atmxmsd]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.atmxmsd]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.atmxmsd]]
modId = "mega_showdown"
mandatory = true
versionRange = "[9.7.6-release-neoforge,)"
ordering = "AFTER"
side = "BOTH"
